### PR TITLE
fix: add img/network to dist

### PR DESCRIPTION
**Pull request by mojoaxel**

### CODE REVIEW

**Comment by mojoaxel** [comment]
Also: at the moment network-styles are completely ignored. see https://github.com/visjs/vis-network/issues/65

**Comment by Thomaash** [comment]
I get `[!] (plugin babel-minify) Error: don't know how to turn this value into a node` when I try to build this.

**Comment by mojoaxel** [comment]
> I get [!] (plugin babel-minify) Error: don't know how to turn this value into a node when I try to build this.

This has propably to do with #69. I'll take a look!

**Comment by mojoaxel** [comment]
> I get [!] (plugin babel-minify) Error: don't know how to turn this value into a node when I try to build this.

I only get this error with vis-util@1.1.5 not with 1.1.4.
@Thomaash Maybe you could have a look at this!?

**Comment by Thomaash** [comment]
It seems that rollup-plugin-babel-minify has a problem with core-js 3, downgrading to core-js 2 seems to work.

**Comment by Thomaash** [comment]
Works with vis-util 1.1.6 :tada:.

**Comment by mojoaxel** [comment]
> Works with vis-util 1.1.6 tada.

I updated to vis-util@1.1.6. 
@Thomaash Please review!

By the way I still get two warning:
```
(!) Plugin rpt2: /media/delphin/Data1/workspaces/workspace_vis/vis-charts/src/index.ts(8,10): semantic error TS2724: Module '"../node_modules/vis-network/lib"' has no exported member 'Network'. Did you mean 'network'
```
```
(!) Broken sourcemap
```

**Comment by Thomaash** [comment]
```
(!) Plugin rpt2: /media/delphin/Data1/workspaces/workspace_vis/vis-charts/src/index.ts(8,10): semantic error TS2724: Module '"../node_modules/vis-network/lib"' has no exported member 'Network'. Did you mean 'network'
```

I know about this but the build files are okay, no idea how to get rid of the message.

```
(!) Broken sourcemap
```

CSS Porter doesn't generate source maps. JavaScript sourcemaps work just fine.
